config/routes.rb
Rails.application.routes.draw do
  get 'order_details/update'
 
 devise_for :admins, skip: :all
 devise_scope :admin do
  get 'admins/sign_in' => 'admins/sessions#new', as: :new_admin_session
  post 'admins/sign_in' => 'admins/sessions#create', as: :admin_session
  delete 'logout' => 'admins/sessions#destroy', as: :destroy_admin_session
end
 
  #devise_for :admins, controllers: {
  #sessions:      'admins/sessions',
  #passwords:     'admins/passwords',
  #registrations: 'admins/registrations'
#}
  namespace :admin do
      root 'homes#index'
      resources :items,only: [:index,:new,:create,:show,:edit,:update]
      resources :genres,only: [:index,:create,:edit,:update]
      resources :customers,only: [:index,:show,:edit,:update]
      resources :orders,only: [:show,:update]
      resources :order_details,only: [:update]
  end

  # namespace :public do
  #   resources :items, only: [:index, :show]
  #   resources :cart_items, only: [:index, :update, :destroy, :create]
  #   delete 'cart_items' => 'cart_items#destroy_all', as: 'cart_item_all'
  #   resources :addresses, only: [:index, :update, :destroy, :create, :edit]
  #   resources :orders, only: [:index, :show]
  # end

  devise_for :customers, controllers: {
  sessions:      'customers/sessions',
  passwords:     'customers/passwords',
  registrations: 'customers/registrations'
}

  scope module: 'public' do
    root to: 'homes#top'
    get '/about', to: 'homes#about'
    get 'customers/my_page', to: 'customers#show'
    get 'customers/unsubscribe', to: 'customers#unsubscribe'
    patch 'customers/withdrawal', to: 'customers#withdrawal', as: 'withdrawal'
    resources :customers, only: [:edit, :update]

    get '/orders/complete', to: 'orders#complete', as: 'complete'
    resources :orders, only: [:new, :create, :index, :show]
    post '/orders/confirm', to: 'orders#confirm', as: 'confirm'
    resources :items, only: [:index, :show]
    resources :cart_items, only: [:index, :update, :destroy, :create]
    delete 'cart_items' => 'cart_items#destroy_all', as: 'cart_item_all'
    resources :addresses, only: [:index, :update, :destroy, :create, :edit]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # namespace :admin do
  #   resources :items, only: [:new, :create, :edit, :update]
  #   resources :customers, only: [:index, :show, :edit, :update]
  # end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  
  def address_all
    "〒" + postal_code + " " + address + " " + name
  end

  validates :name, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  def subtotal
    item.price * amount
  end

  validates :amount, presence: true

end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :last_name, :first_name, :last_name_kana, :first_name_kana,
            :postal_code, :address, :telephone_number, presence:true

  validates :last_name_kana, :first_name_kana,
                 format: {
                   with: /\A[\p{katakana}　ー－&&[^ -~｡-ﾟ]]+\z/,
                   }
  validates :postal_code, :telephone_number,numericality: { only_integer: true}

  validates :email, uniqueness: true

  def full_name
    self.last_name + " " + self.first_name
  end

  def full_name_kana
    self.last_name_kana + " " + self.first_name_kana
  end

  
  def active_for_authentication?
   super && (self.is_deleted == false )
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  validates :is_deleted, inclusion: { in: [true, false]}

  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  attachment :image

  def price_tax
    self.price * 1.1
  end

end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details, dependent: :destroy
  belongs_to :customer

  validates :postal_code, :address, :name, presence:true

  enum payment_method: {"クレジットカード": 0, "銀行振込": 1}
  enum status: {"入金待ち": 0, "入金確認": 1, "製作中": 2 , "発送準備中": 3, "発送済み": 4}

  def full_name
    self.last_name + " " + self.first_name
  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum making_status: {"着手不可": 0,"製作待ち": 1,"製作中": 2,"製作完了": 3}

  def subtotal
    self.proce * self.amount
  end

  def auto_update
    if self.making_status == "製作中"
      self.order.update(status: "製作中")
    end
  end

  def complete_auto_update
    order_details = self.order.order_details
    making_status = order_details.pluck(:making_status)
     if making_status.all?{ |making_status| making_status == "製作完了"}
       self.order.update(status: "発送準備中")
     end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  def index
    @orders = Order.page(params[:page]).per(10)
  end
end

app/controllers/admin/items_controller.rb
class  Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @items = Item.all
    @item = Item.new
  end

  def show
    @item = Item.find(params[:id])
  end

  def new
    @item = Item.new
  end

  def create
    item = Item.new(item_params)
    item.save
    redirect_to item_path(item)
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to admin_item_path(item)
  end

  private
  def item_params
    params.require(:item).permit(:genre_id, :name, :introduction, :image, :price, :is_deleted, :image_id)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!
  def show
    @order = Order.find(params[:id])
    @total = 0
  end

  def update
    @order = Order.find(params[:id])
    temp = order_params
    temp[:status] = temp[:status].to_i
    @order.update(temp)
    if @order.status == "入金確認"
      @order.order_details.each do |d|
        d.update(making_status: "製作待ち")
      end
    end
    redirect_to admin_order_path(@order)
  end

    private

  def order_params
    params.require(:order).permit(:status)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    case resource
      when Customer
        root_path
      when Admin
        admin_root_path
    end
  end
  
  def after_sign_out_path_for(resource)
    if resource == :customer
        new_customer_session_path
    elsif resource == :admin
        new_admin_session_path
    else
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:
    [:last_name, :first_name, :last_name_kana, :first_name_kana,
    :postal_code, :address, :telephone_number])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/order_details_helper.rb
module OrderDetailsHelper
end

app/views/admin/orders/show.html.erb
<div class="row">
    <div class="col-12">
      <h1>注文履歴詳細</h1>
      <table class='table table-hover table-inverse'>
        <%# @order.each do |o| %>
        <tr>
          <td>購入者</td>
          <td><%= @order.name %></td>
        </tr>
        <tr>
          <td>注文日</td>
          <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
        </tr>
        <tr>
          <td>配送先</td>
          <td><%= @order.address %></td>
        </tr>
        <tr>
          <td>支払い方法</td>
          <td><%= @order.payment_method %></td>
        </tr>
        <tr>
          <td>ステータス</td>
          <td><%= @order.status %></td>

          <td><%= form_with model:@order, url: admin_order_path(@order), method: :patch, local: true do |f| %>
              <%#= f.collection_select(:making_status, detail, :id, :making_status, {prompt: "==選択してください=="} ) %>
            	<%#= f.select :making_status, [ ["着手不可", 0], ["制作待ち", 1], ["製作中", 2], ["制作完了", 3] ] %>
            	<%= f.select :status, Order.statuses %> <%= f.submit '更新', class: "btn btn-sm btn-success" %></td>
            	<%#= f.select :status, {0: '入金待ち', 1: '入金確認', 2: '製作中', 3: '発送準備中', 4: '発送済み'} %>
            <% end %>
        </tr>
      </table>
      <table class='table table-hover table-inverse'>
        <thead>
          <tr>
            <th>商品名</th>
            <th>単価(税込み)</th>
            <th>数量</th>
            <th>小計</th>
            <th>製作ステータス</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <% @order.order_details.each do |detail|%>
            <td><%= detail.item.name %></td>
            <td><%= detail.price %></td>
            <!--orderモデルに定義↓-->
            <td><%= detail.amount%></td>
            <td><%= detail.price * detail. amount %></td>
            <% @total += detail.price * detail.amount %>
            <td><%= form_with model:detail, url: admin_order_detail_path(detail.id), method: :patch, local: true do |f| %>
              <%#= f.collection_select(:making_status, detail, :id, :making_status, {prompt: "==選択してください=="} ) %>
            	<%#= f.select :making_status, [ ["着手不可", "着手不可"], ["制作待ち", "制作待ち"], ["製作中", "製作中"], ["製作完了", "製作完了"] ] %>
            	<%= f.select :making_status, OrderDetail.making_statuses.keys %>
            	<%#= f.select :making_status, OrderDetail.making_statuses %>
            	<%= f.submit '更新', class: "btn btn-sm btn-success" %>
            <% end %>
            </td>
          </tr>
            <% end %>
        </tbody>
      </table>

      <table>
        <tr>
          <td>商品合計</td>
          <td><%= @total %></td>
        </tr>
        <tr>
          <td>送料</td>
          <td><%= @order.shipping_cost %></td>
          <!--800べたうちにする？-->
        </tr>
        <tr>
          <td>請求金額合計</td>
          <td><%= @total + @order.shipping_cost %></td>
        </tr>
      </table>
  </div>
</div>