config/routes.rb
Rails.application.routes.draw do
  get 'order_details/update'
 
 devise_for :admins, skip: :all
 devise_scope :admin do
  get 'admins/sign_in' => 'admins/sessions#new', as: :new_admin_session
  post 'admins/sign_in' => 'admins/sessions#create', as: :admin_session
  delete 'logout' => 'admins/sessions#destroy', as: :destroy_admin_session
end
 
  #devise_for :admins, controllers: {
  #sessions:      'admins/sessions',
  #passwords:     'admins/passwords',
  #registrations: 'admins/registrations'
#}
  namespace :admin do
      root 'homes#index'
      resources :items,only: [:index,:new,:create,:show,:edit,:update]
      resources :genres,only: [:index,:create,:edit,:update]
      resources :customers,only: [:index,:show,:edit,:update]
      resources :orders,only: [:show,:update]
      resources :order_details,only: [:update]
  end

  # namespace :public do
  #   resources :items, only: [:index, :show]
  #   resources :cart_items, only: [:index, :update, :destroy, :create]
  #   delete 'cart_items' => 'cart_items#destroy_all', as: 'cart_item_all'
  #   resources :addresses, only: [:index, :update, :destroy, :create, :edit]
  #   resources :orders, only: [:index, :show]
  # end

  devise_for :customers, controllers: {
  sessions:      'customers/sessions',
  passwords:     'customers/passwords',
  registrations: 'customers/registrations'
}

  scope module: 'public' do
    root to: 'homes#top'
    get '/about', to: 'homes#about'
    get 'customers/my_page', to: 'customers#show'
    get 'customers/unsubscribe', to: 'customers#unsubscribe'
    patch 'customers/withdrawal', to: 'customers#withdrawal', as: 'withdrawal'
    resources :customers, only: [:edit, :update]

    get '/orders/complete', to: 'orders#complete', as: 'complete'
    resources :orders, only: [:new, :create, :index, :show]
    post '/orders/confirm', to: 'orders#confirm', as: 'confirm'
    resources :items, only: [:index, :show]
    resources :cart_items, only: [:index, :update, :destroy, :create]
    delete 'cart_items' => 'cart_items#destroy_all', as: 'cart_item_all'
    resources :addresses, only: [:index, :update, :destroy, :create, :edit]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # namespace :admin do
  #   resources :items, only: [:new, :create, :edit, :update]
  #   resources :customers, only: [:index, :show, :edit, :update]
  # end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  
  def address_all
    "〒" + postal_code + " " + address + " " + name
  end

  validates :name, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  def subtotal
    item.price * amount
  end

  validates :amount, presence: true

end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :last_name, :first_name, :last_name_kana, :first_name_kana,
            :postal_code, :address, :telephone_number, presence:true

  validates :last_name_kana, :first_name_kana,
                 format: {
                   with: /\A[\p{katakana}　ー－&&[^ -~｡-ﾟ]]+\z/,
                   }
  validates :postal_code, :telephone_number,numericality: { only_integer: true}

  validates :email, uniqueness: true

  def full_name
    self.last_name + " " + self.first_name
  end

  def full_name_kana
    self.last_name_kana + " " + self.first_name_kana
  end

  
  def active_for_authentication?
   super && (self.is_deleted == false )
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  validates :is_deleted, inclusion: { in: [true, false]}

  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  attachment :image

  def price_tax
    self.price * 1.1
  end

end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details, dependent: :destroy
  belongs_to :customer

  validates :postal_code, :address, :name, presence:true

  enum payment_method: {"クレジットカード": 0, "銀行振込": 1}
  enum status: {"入金待ち": 0, "入金確認": 1, "製作中": 2 , "発送準備中": 3, "発送済み": 4}

  def full_name
    self.last_name + " " + self.first_name
  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum making_status: {"着手不可": 0,"製作待ち": 1,"製作中": 2,"製作完了": 3}

  def subtotal
    self.proce * self.amount
  end

  def auto_update
    if self.making_status == "製作中"
      self.order.update(status: "製作中")
    end
  end

  def complete_auto_update
    order_details = self.order.order_details
    making_status = order_details.pluck(:making_status)
     if making_status.all?{ |making_status| making_status == "製作完了"}
       self.order.update(status: "発送準備中")
     end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    case resource
      when Customer
        root_path
      when Admin
        admin_root_path
    end
  end
  
  def after_sign_out_path_for(resource)
    if resource == :customer
        new_customer_session_path
    elsif resource == :admin
        new_admin_session_path
    else
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:
    [:last_name, :first_name, :last_name_kana, :first_name_kana,
    :postal_code, :address, :telephone_number])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/order_details_helper.rb
module OrderDetailsHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<footer id = footer>
  <div class='container mt-5'>
    <div class='row'>
      <div class='mx-auto'>
        <p class="footer-text">CopyRight NaganoCake</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand navbar-dark ">
  <!-- <a class="navbar-brand" href="#">Always expand</a> -->
  <div id = "header-logo">
    <%#= link_to image_tag(/OnionCone/app/assets/images/Logo.png), root_path %>
      <%= link_to root_path do %>
        <%= image_tag '/assets/Logo.png', size: "100x80" %>
      <% end %>
  </div>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample02" aria-controls="navbarsExample02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <% if admin_signed_in? %>
  <div class="collapse navbar-collapse" id="navbarsExample02">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to ' 商品一覧', admin_items_path,class: 'nav-link text-light' %>
      </li>
      <li class="nav-item">
        <!-- <a class="nav-link" href="#">Link</a> -->
        <%= link_to '会員一覧',admin_customers_path,class: 'nav-link text-light' %>
      </li>
            <li class="nav-item">
        <!-- <a class="nav-link" href="#">Link</a> -->
        <%= link_to '注文履歴一覧',admin_root_path,class: 'nav-link text-light'%>
      </li>
            <li class="nav-item">
        <!-- <a class="nav-link" href="#">Link</a> -->
        <%= link_to 'ジャンル一覧', admin_genres_path, class: 'nav-link text-light' %>
      </li>
            <li class="nav-item">
        <!-- <a class="nav-link" href="#">Link</a> -->
        <%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class: 'nav-link text-light' %>
      </li>
    </ul>
  </div>
</nav>
    <nav class="bg-warning">
      <div class="container">
        <div class="navbar-nav mr-auto">
            <% elsif customer_signed_in? %>
              <div class="collapse navbar-collapse" id="navbarsExample02">
                <%= "ようこそ、 " + customer.last_name + "さん!" %>
                <ul class="navbar-nav mr-auto text-white" >
                  <li class="nav-item">
                    <%= link_to ' My Page', customers_my_page_path, class: 'text-white' %>
                  </li>
                  <li class="nav-item">
                    <%= link_to ' Sweets', items_path, class: 'text-white' %>
                  </li>
                  <li class="nav-item">
                    <%= link_to ' Cart', cart_items_path, class: 'text-white' %>
                  </li>
                  <li class="nav-item">
                    <%= link_to " Log Out", destroy_customer_session_path, method: :delete, class: 'text-white' %>
                  </li>
                </ul>
              </div>
              <div class "row">
                  <form class="form-inline my-2 my-md-0">
                    <input class="form-control" type="text" placeholder="検索">
                  </form>
              </div>
            <% else %>
              <div class="collapse navbar-collapse" id="navbarsExample02">
                <ul class="navbar-nav mr-auto">
                  <li class="nav-item"><%= link_to ' About', about_path, class: 'text-white' %></li>
                  <li class="nav-item"><%= link_to ' Sweets', items_path , class: 'text-white' %></li>
                  <li class="nav-item"><%= link_to ' Sign Up', new_customer_registration_path, class: 'text-white' %></li>
                  <li class="nav-item"><%= link_to ' Log In', new_customer_session_path, class: 'text-white' %></li>
                </ul>
              </div>
            <% end %>
        </div>
      </div>
    </nav>
</header>

app/views/layouts/application.html.erb
umemoto.kurumi
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
    <%= render 'layouts/header', { customer: current_customer} %>
    </header>
        <%= yield %>
    <footer><%= render 'layouts/footer', { customer: current_customer} %></footer>
  </body>
</html>